version: '3.1'

services:

  db:
    image: mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - obs-network
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: obsdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  adminer:
    image: adminer
    restart: unless-stopped
    networks:
      - obs-network
    ports:
      - 8081:8080

networks:
  obs-network:
    name: obs-network
